### ISSUE TITLE
Failure to Bypass Imperva / Incapsula WAF: Receiving Error Code 15

### ISSUE THREAD

**Issue by iamvinny** [julianjm/waf_bypadd#1]
## Issue Description:
I have been attempting to bypass a website that utilizes Incapsula WAF using the provided extension. However, it appears that the extension is not functioning as expected, despite following the installation instructions delineated in the ReadMe file.

## Environment:
Extension Version: v.0.9
Jython Version: 2.7.3
Burp Suite Version: v2023.10.1.1
Browsers: Firefox / Chromium (Burp's Browser)

## Steps to Reproduce:
1. Installed Jython and configured it with Burp Suite according to the instructions in the ReadMe file.
2. Installed the extension successfully.
3. Selected all the intercept options (Proxy, Scanner, Repeater)
4. Attempted to intercept links that are protected by Incapsula WAF.

## Expected Behavior:
The extension should allow the interception of links behind Incapsula WAF without errors.

## Observed Behavior:
Upon trying to intercept the links, an error with code 15 is consistently presented, the page won't open until I remove the Burp Local Proxy `128.0.0.1:8080` from the browser.

## Screenshots:

<img width="732" alt="Screenshot 2023-09-24 at 5 34 58 PM" src="https://github.com/julianjm/waf_bypadd/assets/29668752/b13c0faa-c7c5-495f-83dd-310fee3c6220">

<img width="951" alt="image" src="https://github.com/julianjm/waf_bypadd/assets/29668752/a59c1e37-0138-48bc-b9bc-51e65be6a109">

<img width="1368" alt="Screenshot 2023-09-24 at 5 38 28 PM" src="https://github.com/julianjm/waf_bypadd/assets/29668752/e3187f6f-e7c2-4b76-ad40-5c91d0ef25b0">

## Additional Information:
If there are any additional configurations or settings that need to be adjusted to address this issue, please advise. Furthermore, any insights or suggestions to resolve this problem would be highly appreciated.

## Request:
Could the maintainers or the community provide any assistance or insights into resolving this issue? Is there any known workaround or upcoming fix to address this issue?

Thanks in advance for your time and consideration.

**Comment by julianjm** [comment]
Hi. First of all, you shouldn't be able to bypass a properly configured WAF. This extension is intented do be used on firewalls that don't scan the full payload, but just the first bytes. 

Also, keep in mind that it only modifies the body of POST requests.
